# Generated by Django 5.0.2 on 2024-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee_bags',
            name='CBP',
            field=models.ImageField(upload_to='Images/Coffee-Bags2'),
        ),
    ]
