# Generated by Django 5.0.2 on 2024-03-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RName', models.CharField(max_length=80)),
                ('RDate', models.DateTimeField(auto_now_add=True)),
                ('RPersons', models.PositiveIntegerField()),
            ],
        ),
    ]
