# Generated by Django 5.0.2 on 2024-03-14 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reserve_rtime_alter_reserve_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='RTime',
            field=models.TimeField(default=datetime.datetime(2024, 3, 14, 12, 18, 10, 764905, tzinfo=datetime.timezone.utc)),
        ),
    ]
