# Generated by Django 5.0.2 on 2024-03-14 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reserve_rtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='RTime',
            field=models.TimeField(default=datetime.datetime(2024, 3, 14, 16, 45, 30, 856430, tzinfo=datetime.timezone.utc)),
        ),
    ]
